[tool.mypy]
follow_imports = "silent"
ignore_missing_imports = true
show_error_codes = true


[tool.black]
line-length = 120

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
profile = "black"
lines_after_imports = 2
